---
name: General Purpose
about: This template serves as a structured format for users to provide detailed information about encountered bugs.
title: 'triage: '
labels: 'status: new'
assignees: ''

---

<!--Thanks for taking the time to fill out this bug report! -->
<!--Before you submit, please search open issues to see if your bug has already been reported. -->

## Description
> Please provide a clear and concise description of what the bug is. If applicable, add screenshots & logs to help explain your problem.

## Possible solution(s) (if any)
> Please provide a possible solution to the bug. If you don't have one, that's okay, just leave this section blank.

## Steps to reproduce (if any)
> Please provide detailed steps for reproducing the issue.

## Additional context (if any)
> Add any other context about the problem here.
